name: Build
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "zulu"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Tests
        run: ./gradlew testDebugUnitTest --scan

      - name: Coverage Report
        run: ./gradlew jacocoFullReport

      - name: Assemble
        run: ./gradlew assembleDebug

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: build/reports/jacoco/jacocoFullReport/jacocoFullReport.csv

      - name: Commit and push the badge (if it changed)
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: commit coverage badge ${{ github.run_attempt }}
          add: '*.svg'

      - name: Test Coverage Report Upload
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: build/reports/jacoco/jacocoFullReport/html/

      - name: APK Upload
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
